export const CODEX_HOOK_TIMEOUT_SECONDS = 259_200;
export const DEFAULT_BROWSER_WAIT_TIMEOUT_MS = (CODEX_HOOK_TIMEOUT_SECONDS - 30) * 1_000;
export const DEFAULT_BRIDGE_SESSION_TTL_MS = CODEX_HOOK_TIMEOUT_SECONDS * 1_000;
